spring.application.name=parkiyo

# Disable DB for now
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Disable cache (auto refresh HTML)
spring.thymeleaf.cache=false