spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

parkiyo.bootstrap.enabled=false
parkiyo.bootstrap.demo-slots-enabled=false

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
